services:
  php:
    container_name: php-service
    restart: unless-stopped
    build:
      args:
        user: '${WWWUSER}'
        uid: '${WWWUID}'
        group: '${WWWGROUP}'
      context: .
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - backend
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - backend
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
networks:
  backend:
    driver: bridge
